name: plexams-server
version: '0.9.0.0'
synopsis: Server for planning exams
description: See README at <https://github.com/obcode/plexams#readme>
license: BSD3
github: PumaD/plexams
maintainer: Felician Pinkert <pinkert@hm.edu>
category: Plexams

ghc-options: -Wall

dependencies:
  - base  >= 4.7 && < 5
  - aeson
  - servant-server
  - text
  - wai
  - warp
  - plexams-core
  - plexams-cli
  - optparse-applicative
  - mtl
  - directory
  - time
  - bytestring
  - containers
  - yaml


library:
  source-dirs: src

executables:
  plexams-server:
    main: Plexams-Server.hs
    source-dirs: app
    dependencies:
      - plexams-server
