name: plexams-cli
version: '0.9.0.0'
synopsis: Command line interface for planning exams
description: See README at <https://github.com/obcode/plexams#readme>
license: BSD3
github: obcode/plexams
maintainer: Oliver Braun <ob@obraun.net>
category: Plexams

ghc-options: -Wall

dependencies:
  - base  >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - containers
    - directory
    - optparse-applicative
    - plexams-core
    - plexams-generators
    - pretty-show
    - text
    - time

executables:
  plexams:
    main: Plexams.hs
    source-dirs: app
    dependencies:
      - plexams-cli
  plexams-helper:
    main: Plexams-Helper.hs
    source-dirs: app
    dependencies:
      - plexams-cli
