name: plexams-cli
version: '1.0.6.0'
synopsis: Command line interface for planning exams
description: See README at <https://github.com/obcode/plexams#readme>
license: BSD3
github: obcode/plexams
maintainer: Oliver Braun <ob@obraun.net>
category: Plexams

ghc-options: -Wall

dependencies:
  - base  >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-pretty
    - bytestring
    - containers
    - directory
    - optparse-applicative
    - plexams-core
    - plexams-generators
    - plexams-validation
    - plexams-datamgmt
    - pretty-show
    - text
    - time
    - yaml
    - word8

executables:
  plexams:
    main: Plexams.hs
    source-dirs: app/plexams
    dependencies:
      - plexams-cli
      - plexams-core
      - plexams-datamgmt
      - text
      - directory
  plexams-helper:
    main: Plexams-Helper.hs
    source-dirs: app/plexams-helper
    dependencies:
      - plexams-cli
