resolver: lts-9.21
packages:
    - ./plexams-core
    - ./plexams-datamgmt
    - ./plexams-validation
    - ./plexams-cli
    - ./plexams-generators
    - ./plexams-server
# local-bin-path: ./elexams/resources
