name: plexams-core
version: "1.1.0.1"
synopsis: Core modules for planning exams
description: See README at <https://github.com/obcode/plexams#readme>
license: BSD3
github: obcode/plexams
maintainer: Oliver Braun <ob@obraun.net>
category: Plexams

ghc-options: -Wall -Werror

dependencies:
  - base  >= 4.7 && < 5
  - aeson
  - aeson-pretty
  - bytestring
  - containers
  - mtl
  - text
  - text-show
  - time
  - vector
  - yaml

library:
  source-dirs: src
  other-modules:
    - Plexams.PlanManip.Exam
    - Plexams.PlanManip.Invigilator
    - Plexams.PlanManip.Room
    - Plexams.PlanManip.StudentRegs
