name: plexams-core
version: '0.9.0.0'
synopsis: Core modules for planning exams
description: See README at <https://github.com/obcode/plexams#readme>
license: BSD3
github: obcode/plexams
maintainer: Oliver Braun <ob@obraun.net>
category: Plexams

ghc-options: -Wall

dependencies:
  - base  >= 4.7 && < 5
  - aeson
  - aeson-pretty
  - bytestring
  - containers
  - mtl
  - text
  - text-show
  - time
  - vector
  - yaml

library:
  source-dirs: src
  other-modules:
    - Plexams.Validation.Rooms
    - Plexams.Validation.ScheduledExams
    - Plexams.Validation.Sources
    - Plexams.Validation.Exports
